-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 11:42:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `marketplace`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(6) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`ADMINISTRADOR` (
  `USUÁRIO_id` INT NOT NULL,
  PRIMARY KEY (`USUÁRIO_id`),
  CONSTRAINT `fk_ADMINISTRADOR_USUÁRIO1`
    FOREIGN KEY (`USUÁRIO_id`)
    REFERENCES `marketplace`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`VENDEDOR` (
  `USUÁRIO_id` INT NOT NULL,
  `ADMINISTRADOR_USUÁRIO_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_analise` DATE NOT NULL,
  PRIMARY KEY (`USUÁRIO_id`),
  INDEX `fk_VENDEDOR_ADMINISTRADOR1_idx` (`ADMINISTRADOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_VENDEDOR_USUÁRIO`
    FOREIGN KEY (`USUÁRIO_id`)
    REFERENCES `marketplace`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDEDOR_ADMINISTRADOR1`
    FOREIGN KEY (`ADMINISTRADOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`ADMINISTRADOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`COMPRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`COMPRADOR` (
  `USUÁRIO_id` INT NOT NULL,
  PRIMARY KEY (`USUÁRIO_id`),
  CONSTRAINT `fk_COMPRADOR_USUÁRIO1`
    FOREIGN KEY (`USUÁRIO_id`)
    REFERENCES `marketplace`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`PRODUTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `VENDEDOR_USUÁRIO_id` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `estoque` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PRODUTO_VENDEDOR1_idx` (`VENDEDOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`VENDEDOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`IMAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`IMAGEM` (
  `imagem` VARCHAR(100) NOT NULL,
  `PRODUTO_id` INT NOT NULL,
  PRIMARY KEY (`PRODUTO_id`, `imagem`),
  INDEX `fk_IMAGEM_PRODUTO1_idx` (`PRODUTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_IMAGEM_PRODUTO1`
    FOREIGN KEY (`PRODUTO_id`)
    REFERENCES `marketplace`.`PRODUTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`PEDIDO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `COMPRADOR_USUÁRIO_id` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status_pedido` VARCHAR(45) NOT NULL,
  `previsao_entrega` DATETIME NULL,
  `efetivacao` DATETIME NULL,
  `total` DECIMAL NOT NULL,
  `pagamento_forma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PEDIDO_COMPRADOR1_idx` (`COMPRADOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_COMPRADOR1`
    FOREIGN KEY (`COMPRADOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`COMPRADOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`ENDERECO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USUÁRIO_id` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `tipo_endereco` VARCHAR(45) NOT NULL,
  `endereco_principal` TINYINT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ENDERECO_USUÁRIO1_idx` (`USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_USUÁRIO1`
    FOREIGN KEY (`USUÁRIO_id`)
    REFERENCES `marketplace`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`PEDIDO_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`PEDIDO_PRODUTO` (
  `PEDIDO_id` INT NOT NULL,
  `PRODUTO_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL NOT NULL,
  INDEX `fk_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_id` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUTO_PEDIDO1_idx` (`PEDIDO_id` ASC) VISIBLE,
  PRIMARY KEY (`PEDIDO_id`, `PRODUTO_id`),
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id`)
    REFERENCES `marketplace`.`PEDIDO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_id`)
    REFERENCES `marketplace`.`PRODUTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`CARRINHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`CARRINHO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `COMPRADOR_USUÁRIO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CARRINHO_COMPRADOR1_idx` (`COMPRADOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_CARRINHO_COMPRADOR1`
    FOREIGN KEY (`COMPRADOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`COMPRADOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`CARRINHO_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`CARRINHO_PRODUTO` (
  `CARRINHO_id` INT NOT NULL,
  `PRODUTO_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`CARRINHO_id`, `PRODUTO_id`),
  INDEX `fk_CARRINHO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_id` ASC) VISIBLE,
  INDEX `fk_CARRINHO_has_PRODUTO_CARRINHO1_idx` (`CARRINHO_id` ASC) VISIBLE,
  CONSTRAINT `fk_CARRINHO_has_PRODUTO_CARRINHO1`
    FOREIGN KEY (`CARRINHO_id`)
    REFERENCES `marketplace`.`CARRINHO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRINHO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_id`)
    REFERENCES `marketplace`.`PRODUTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`LISTA_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`LISTA_PEDIDO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `COMPRADOR_USUÁRIO_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LISTA_PEDIDO_COMPRADOR1_idx` (`COMPRADOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_LISTA_PEDIDO_COMPRADOR1`
    FOREIGN KEY (`COMPRADOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`COMPRADOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`LISTA_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`LISTA_PRODUTO` (
  `LISTA_PEDIDO_id` INT NOT NULL,
  `PRODUTO_id` INT NOT NULL,
  PRIMARY KEY (`LISTA_PEDIDO_id`, `PRODUTO_id`),
  INDEX `fk_LISTA_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_id` ASC) VISIBLE,
  INDEX `fk_LISTA_PEDIDO_has_PRODUTO_LISTA_PEDIDO1_idx` (`LISTA_PEDIDO_id` ASC) VISIBLE,
  CONSTRAINT `fk_LISTA_PEDIDO_has_PRODUTO_LISTA_PEDIDO1`
    FOREIGN KEY (`LISTA_PEDIDO_id`)
    REFERENCES `marketplace`.`LISTA_PEDIDO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LISTA_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_id`)
    REFERENCES `marketplace`.`PRODUTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`CHAT` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `COMPRADOR_USUÁRIO_id` INT NOT NULL,
  `VENDEDOR_USUÁRIO_id` INT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CHAT_COMPRADOR1_idx` (`COMPRADOR_USUÁRIO_id` ASC) VISIBLE,
  INDEX `fk_CHAT_VENDEDOR1_idx` (`VENDEDOR_USUÁRIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_COMPRADOR1`
    FOREIGN KEY (`COMPRADOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`COMPRADOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_USUÁRIO_id`)
    REFERENCES `marketplace`.`VENDEDOR` (`USUÁRIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`MENSAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`MENSAGEM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USUÁRIO_id` INT NOT NULL,
  `CHAT_Id` INT NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  INDEX `fk_MENSAGEM_CHAT1_idx` (`CHAT_Id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_MENSAGEM_USUÁRIO1`
    FOREIGN KEY (`USUÁRIO_id`)
    REFERENCES `marketplace`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MENSAGEM_CHAT1`
    FOREIGN KEY (`CHAT_Id`)
    REFERENCES `marketplace`.`CHAT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`AVALIACAO` (
  `PEDIDO_id` INT NOT NULL,
  `PRODUTO_id` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `data_avaliacao` DATETIME NULL,
  PRIMARY KEY (`PEDIDO_id`, `PRODUTO_id`),
  INDEX `fk_AVALIACAO_PEDIDO_PRODUTO1_idx` (`PEDIDO_id` ASC, `PRODUTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_AVALIACAO_PEDIDO_PRODUTO1`
    FOREIGN KEY (`PEDIDO_id` , `PRODUTO_id`)
    REFERENCES `marketplace`.`PEDIDO_PRODUTO` (`PEDIDO_id` , `PRODUTO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
